version: '3'

services:
  web:
    image: noco
    build: .
    command: gunicorn -b 0.0.0.0:5000 noco.wsgi:app
    env_file:
      - ./.env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    volumes:
      - ./noco:/code/noco
    ports:
      - "5000:5000"
  rabbitmq:
    image: library/rabbitmq:3.8.6-alpine
  rabbitmq-management:
    image: library/rabbitmq:3.8.6-management-alpine
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=M49GNnMu0mX8
  celery:
    image: noco
    command: "celery worker -A noco.celery_app:app"
    env_file:
      - ./.env
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
